version: '3.8'

networks:
  default:
    external: false
    name: agreena-app-local

services:
  postgres:
    container_name: 'agreena-app-postgres-local'
    image: postgres
    volumes:
      - dbdata:/var/lib/postresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  dbdata:
    name: agreena-app-postgres-volume

# services:
#   agreena-app-postgres:
#     image: 'postgres:13-alpine'
#     command: postgres -c 'max_connections=1000'
#     restart: always
#     container_name: agreena-app-postgres-local
#     environment:
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_DB=${POSTGRES_DB}
#     volumes:
#       - ./db_data:/var/lib/postgresql/data
#     ports:
#       - '${DB_PORT}:5432'
